### ISSUE TITLE
undefined function add_filter

### ISSUE THREAD

**Issue by riesurya** [gambitph/WP-OTF-Regenerate-Thumbnails#12]
Hi Benjamin,

It's a great plugin ( as predecessor bfi_thumb, i love bfi_thumb until yesterday found WP-OTF-Regenerate-Thumbnails )

btw, on scenario :
WP 4.2.2
WP-OTF-Regenerate-Thumbnails v.0.3
Mode: theme included file ( directly )
Fatal error: Call to undefined function add_filter() in otf_regen_thumbs.php on line 22

it's not happen if loaded as plugin

May you explain and ( may be fix this ) ?

Thanks anyway :)

**Comment by oherman** [comment]
Hi, in behalf of Benjamin, I took notice of the problem and made a slight change.
Please pull a new copy and see if this fixes the problem. So far, we don't have problems like the one you mentioned. We have been embedding this plugin in our own products and so far no problems.

Reopen if you do run into it.

**Comment by riesurya** [comment]
@oherman 
Thank you for fix +1: 
It works as promised :)
