### ISSUE TITLE
If the image requested is larger than the image uploaded

### ISSUE THREAD

**Issue by FellowshipAgency** [gambitph/WP-OTF-Regenerate-Thumbnails#2]
If you request an image size but the uploaded image is smaller than the size you're requesting, the image returned is wrong.

I believe native WordPress will return the fullsized image, but with this plugin you instead get the thumbnail image blown up to be the size asked for.

**Comment by bfintal** [comment]
Hey @Rubious, I did some tests but I couldn't replicate it. Would you be able to give a step by step on how to test it?

I tried using `the_post_thumbnail` with a named size and also an array width & height. I used a pre-uploaded small image.

**Comment by FellowshipAgency** [comment]
Strange, it doesn't seem to happen on a brand new install. Must be a conflict with my theme or plugins. I'll look into it, sorry about that.

**Comment by bfintal** [comment]
No problem! Let me know :)

**Comment by bfintal** [comment]
Closing this for the meantime :+1:
