### ISSUE TITLE
Notices after activation

### ISSUE THREAD

**Issue by remyperona** [gambitph/WP-OTF-Regenerate-Thumbnails#3]
Hi,

Love your plugin idea, that would be a great replacement for regenerate thumbnails. I tried to add it to one my website in development, but after activation I got a bunch of notices on the front-page : 
- Notice: Undefined index: full in /wp-content/plugins/otf-regenerate-thumbnails/otf_regen_thumbs.php on line 94
- Notice: Undefined index: original in /wp-content/plugins/otf-regenerate-thumbnails/otf_regen_thumbs.php on line 96

The basic image sizes are defined in settings ->medias, and I don't have any custom image sizes defined. Hope that  can help you.

**Comment by inspiraaz** [comment]
I got the same problem.
This plugin fails when image size is full, for example:
wp_get_attachment_image_src( $image, 'full' )
