### ISSUE TITLE
Use for non "Featured Images"

### ISSUE THREAD

**Issue by generatepress** [gambitph/WP-OTF-Regenerate-Thumbnails#6]
Love the script - nice and simple always wins.

However, one of my plugins relies on a custom field for the URL to an image which I want to have the option to be resized/cropped.

I have this working when users use the "Featured Image" metabox using the_post_thumbnail, but what can I do when the image is coming from another source? Am I out of luck?

Thanks!

**Comment by bfintal** [comment]
If you're using `the_post_thumbnail` and feeding it a size array that your users can change, then OTF should be able to pick up those changes. You can also use `add_image_size` and change that size.

**Comment by generatepress** [comment]
Yea I have it working with the_post_thumbnail - works awesome, was just wondering if there was a way to resize an image being called from a custom metabox as well.

**Comment by bfintal** [comment]
How are you calling the image from the custom metabox?

**Comment by generatepress** [comment]
It's just a URL to the image.

**Comment by bfintal** [comment]
Might also need to use `wp_get_attachment_image` for that

**Comment by generatepress** [comment]
Perfect, got it working.

Thanks!

**Comment by bfintal** [comment]
:+1:
