### ISSUE TITLE
Photon issue

### ISSUE THREAD

**Issue by generatepress** [gambitph/WP-OTF-Regenerate-Thumbnails#8]
I just noticed that while using Jetpack's Photon module that the resizer uses the height as the dimension to crop from.

So if you have it set as 1200x300, the image will end up being 305x300 or something similar.

I did a quick search and noticed people have been having problems with Photon and image resizing in WordPress for a while, but I figured I would mention it here just in case there's something in the script you can tweak.

Feel free to close this if it's simply a Photon issue and nothing to do with your script :)

**Comment by oherman** [comment]
Normally we'd tell this is a Jetpack issue and something we shouldn't fix.
However we've been told it will take a while before this is fixed. Many of our plugins also have problems like this.

Check the latest commit for a workaround that will address the issue in the meantime.
